### PR TITLE
make selftest() work

### PR DESCRIPTION
**Pull request by hb9cwp**
Add declaration for ipv6, and temporarily disable missing symbol dasm_checkstep.
With these changes, selftest() runs but outputs 'integrity check failed'.

### CODE REVIEW

**Comment by hb9cwp** [comment]
If `DASM_CHECKS` is undefined (e.g. no checks are desired at run-time), then `dasm_checkstep()` is an undefined symbol at run-time. 

This fix attempts to make sure that macro replacement is not optimized away, even though sub-optimal at run-time compared to the previous `#define dasm_checkstep(a, b)   0`. Probably, there is a smarter way to fix that with less code and smaller impact on run-time.

**Comment by eugeneia** [comment]
@hb9cwp See https://github.com/SnabbCo/snabbswitch/pull/724 for the current LuaJIT/DynASM upgrade and https://github.com/eugeneia/snabbswitch/tree/esp2 for a branch containing a working ESP library.

Since you seem to be interested in `lib.ipsec.esp`: be warned that the code is neither production ready nor am I convinced that it actually satisfies the RFC specs. If you find any errors I would be very thankful to know about those. Happy hacking!

**Comment by hb9cwp** [comment]
@eugeneia Thanks for your hints. Currently, I am debugging selftest() in my fork of your esp2 branch. Apart from RFC-compliance (which is not important at all for my prototype), there is only a two byte mismatch between input and output datagrams, e.g. the Next Header byte at offset 20, and the byte at offset 19. This looks as if there is a problem between encapsulate() and/or decapsulate(). The good news is that encryption and decryption of the payload appears to work! 
If you don't mind, I will continue to push changes to my branch which will show up here too.

**Comment by eugeneia** [comment]
@hb9cwp That was a bug in the test, I fixed (and rebased, sorry) the `esp2` branch and it should work now, try a `git pull --rebase`. Sorry for the confusion, I did not expect anyone to use that branch. By the way, the bug was related to an important culprit: the `encapsulate` and `decapsulate` methods destroy their input packets. I have just updated the [documentation](https://github.com/eugeneia/snabbswitch/tree/esp2/src/lib/ipsec#ipsecesp-libipsecesp) of `encapsulate` to reflect this (it failed to do so until now). E.g. you need to do this:

```
p1 = <somepacket>
p_enc = enc:encapsulate(p1)
-- p1 is now clobbered, don't refer to it, but it is not free'd so you
-- would usually do that now:
packet.free(p1)
p2 = dec:decapsulate(p_enc)
-- Now the same holds true for p_enc
```

**Comment by hb9cwp** [comment]
@eugeneia Thanks Max for your help! selftest() is now passing, and I can include `lib.ipsec.esp` into my experiment :-) Closing PR.

**Pull request closed without merging**
