### PR TITLE
DynASM implementation of AES-GCM encryption

### PR DESCRIPTION
**Pull request by corsix**
Addresses https://github.com/snabbnfv-goodies/snabbswitch/issues/28

Requires https://github.com/LuaJIT/LuaJIT/pull/119 and https://github.com/LuaJIT/LuaJIT/pull/120

### CODE REVIEW

**Comment by eugeneia** [comment]
:+1: Looks awesome! Will check it out more closely tomorrow.

**Comment by eugeneia** [comment]
@corsix I have merged with the LuaJIT v2.1 branch but still get these build errors:

```
ASM       obj/lib/ipsec/aes_128_gcm_avx_dasl.o
lib/ipsec/aes_128_gcm_avx.dasl:95: error: unknown statement `vaesenc':
      | vaesenc xmm(i), xmm(i), xmm(t_key)
lib/ipsec/aes_128_gcm_avx.dasl:106: error: unknown statement `vaesenclast':
    | vaesenclast xmm(i), xmm(i), xmm(t_key)
lib/ipsec/aes_128_gcm_avx.dasl:206: error: unknown statement `vaesenclast':
      | vaesenclast xmm(j), xmm(j), xmm(t[2])
lib/ipsec/aes_128_gcm_avx.dasl:209: error: unknown statement `vaesenclast':
      | vaesenclast xmm(t[3]), xmm(j), xmm(t[2])
lib/ipsec/aes_128_gcm_avx.dasl:251: error: unknown statement `vaesenc':
    | vaesenc xmm(x), xmm(x), [arg1+16*i]
lib/ipsec/aes_128_gcm_avx.dasl:253: error: unknown statement `vaesenclast':
  | vaesenclast xmm(x), xmm(x), [arg1+16*10]
lib/ipsec/aes_128_gcm_avx.dasl:442: error: unknown statement `vaeskeygenassist':
    | vaeskeygenassist xmm2, xmm1, i < 9 and 2^(i-1) or 27*(i-8)
lib/ipsec/aes_128_gcm_avx.dasl:*: info: 7 errors in input file -- no output file generated.
make[1]: *** [obj/lib/ipsec/aes_128_gcm_avx_dasl.o] Error 1
make[1]: Leaving directory `/home/max/snabbswitch/src'
make: *** [all] Error 2
```

Any hints?

**Comment by corsix** [comment]
You need to ensure said PRs are merged into your Lua-mode-DynASM (as it has its own - modified - copy of the DynASM code, as opposed to making use of the copy of DynASM from the ambient LuaJIT).

**Comment by eugeneia** [comment]
@capr I hear you might know how I do this?

**Comment by capr** [comment]
@eugeneia Yap, I'll get to it. I will PR `SnabbCo/snabbswitch:next` with it, is that ok or does that mean waiting too long for it? (I mean PR must be accepted there first then you pull etc., so I can PR you directly, not sure which is best)

**Comment by lukego** [comment]
@capr if you PR to the master branch on SnabbCo then @eugeneia can merge it directly without waiting for it to land on next. (master branch is then like a stable base for building topic branches on that can be merged into multiple destinations)

**Comment by capr** [comment]
@lukego ok I'll PR `SnabbCo/snabbswitch:master`, coming up

**Comment by eugeneia** [comment]
@capr Better yet PR to `eugeneia/snabbswitch:esp`, that's where its supposed to go!

Edit: E.g. that's where I need it right now, we can merge it into upstream later.

**Comment by lukego** [comment]
@eugeneia I disagree on Git workflow. The DynASM upgrade is of general interest and it would be best to make it widely available from the start.

I see two issues here:
1. Which commit to base the dynasm upgrade topic branch on.
2. Which branch(es) to PR it to.

The base commit is important. If the dynasm upgrade branch is based on current master then it is easy to merge onto any branch that is up-to-date with the master branch. For example you can merge it onto your ESP branch and @xrme could also merge it onto his 100G development branch and I can merge it onto my asm-hacking branches and @wingo can merge it onto his podhashmap branch and so on. On the other hand if the DynASM upgrade is based on your ESP branch then it would force the rest of us to merge your ESP commits at the same time (or perform rebases that will likely lead to conflicts later).

The Pull Requests seem less important. There doesn't need to be a formal PR at all: anybody can merge the branch provided that they know where to find it. However, I do see value in submitting the PR to master because it is a central point to make the DynASM upgrade discoverable to people who want to merge/test/review it and are not tracking your ESP branch.

**Comment by wingo** [comment]
Just wanted to chime in to say thank you for this work!  I am looking forward to using it in our optimized AVX2 streaming copy routines.  Having 8 more registers to work with will be great.  If it happens to come as a PR based on master, that's even better for me fwiw :)

**Comment by wingo** [comment]
https://github.com/SnabbCo/snabbswitch/pull/705 for a PR for the LuaJIT changes.

**Comment by eugeneia** [comment]
@corsix After merging with LuaJIT v2.1 I get the following error, any hints by chance?

```
dasm.lua:142: ./snabb: undefined symbol: dasm_checkstep
stack traceback:
    core/main.lua:126: in function <core/main.lua:124>
    [C]: in function '__index'
    dasm.lua:142: in function 'checkstep'
    dasm.lua:210: in function 'build'
    obj/lib/ipsec/aes_128_gcm_avx_dasl.o.gen:689: in main chunk
    [C]: in function 'require'
    lib/ipsec/aes_128_gcm.lua:4: in main chunk
    [C]: in function 'require'
    lib/ipsec/esp.lua:6: in main chunk
    [C]: in function 'require'
    program/snsh/snsh.lua:29: in function <program/snsh/snsh.lua:29>
    core/lib.lua:409: in function 'dogetopt'
    program/snsh/snsh.lua:63: in function 'run'
    core/main.lua:58: in function <core/main.lua:32>
    [C]: in function 'xpcall'
    core/main.lua:155: in main chunk
    [C]: at 0x0044e440
    [C]: in function 'pcall'
    core/startup.lua:1: in main chunk
    [C]: in function 'require'
    [string "require "core.startup""]:1: in main chunk
EXITCODE: 1
```

**Comment by eugeneia** [comment]
@corsix Nevermind, apparently we failed to define `DASM_CHECKS` in the Makefile.

**Comment by hb9cwp** [comment]
Searching where (e.g. which Makefile) the `#define` for this macro `DASM_CHECKS`   is supposed to go.
Hacking it directly into `lib/luajit/dynasm/dasm_x86.h` does not resolve the undefined `dasm_checkstep` yet!?

**Comment by hb9cwp** [comment]
Currently, `dasm_x86.h` is not included at compile time at all. Thus the macro `DASM_CHECKS` does / can not have any effect...

**Comment by capr** [comment]
The makefile needs to include dasm_x86.c with DASM_CHECKS defined.

**Comment by capr** [comment]
I think something else is going on since this was working before with the same makefile no?

**Comment by hb9cwp** [comment]
Could you maybe direct me to a branch that was working, so I can compare and try to figure out the differences, e.g. what went missing? 
Was your branch working, or do you have a more recent version of `https://github.com/corsix/snabbswitch/tree/0b10bcd9a077fd65308305fcf3e9a82d14297d97/src/apps/ipsec`? Thanks.

**Comment by capr** [comment]
I meant that dynasm-luamode is used currently in snabb and it works. And I know for a fact that it cannot work without dasm_checkstep() so DASM_CHECKS was probably defined somewhere as well.

**Comment by capr** [comment]
strange thing is, I cannot find any reference to dasm_x86.c or DASM_CHECKS anywhere in that makefile so I don't know how it worked before. Lemme check the history.

**Comment by hb9cwp** [comment]
Provided `DASM_CHECKS` is defined, `dasm_checkstep()` is actually defined in `lib/luajit/dynasm/dasm_x86.h`, and not in `dasm_x86.c`. 
But also this header file does not get included or compiled, so `dasm_checkstep()` will never end up in an object file...

**Comment by capr** [comment]
but dasm_x86.c does include that header

**Comment by hb9cwp** [comment]
Actually, it looks as if `src/lib/luajit/dynasm/dasm_x86.h` is unused and redundant. But the other header file with the same name (and content) `src/dasm_x86.h` is included indeed. 

make throws a syntax error if I `#define DASM_CHECKS` in `src/dasm_x86.h` ... 
Ahh, because `src/dasm_proto.h` defines a prototype for `dasm_checkstep()` ...
If I insert a `#define DASM_CHECKS` near the top of `src/dasm_proto.h`, both make and execution succeed :-)
Thus a `gcc` in a Makefile might miss a `-DDASM_CHECKS`, but where?

**Comment by hb9cwp** [comment]
The problem is in `src/dasm_proto.h` for the `else` case where `DASM_CHECKS` is undefined, e.g. when no checks at run time are desired: Somehow the short-cut definition of `dasm_checkstep()` fails to evaluate a `0`. 

All is well with this change, although the function call with return value 0 might generate much more code than it previous definition as macro the evaluates to zero:

```
#ifdef DASM_CHECKS
/* Optional sanity checker to call between isolated encoding steps. */
DASM_FDEF int dasm_checkstep(Dst_DECL, int secmatch);
#else
/*#define dasm_checkstep(a, b)  0*/
DASM_FDEF int dasm_checkstep(Dst_DECL, int secmatch) {return 0;}
#endif
```

Has this code path not been tested yet, as `DASM_CHECKS` were always defined previously? Or does some (recent?) code optimization now lead to a compile error with this short-cut macro substitution?

**Comment by hb9cwp** [comment]
See my proposed fix in PR #9 in branch esp2.

**Comment by capr** [comment]
dynasm-luamode is not supposed to run without DASM_CHECKS which is why that code path hasn't been tested. Sure that hack works, but isn't it easier to just invoke the compiler with `-DDASM_CHECKS` ?

**Comment by hb9cwp** [comment]
OK, but I could not identify the right place in `src/Makefile` or so to add `-DDASM_CHECKS` in a meaningfull place, such as `DEBUG = ...`.
Therefore, I propose to add the `DASM_CHECKS` flag to `src/dasm_proto.h` where I have it currently `#undef`-ined. We could just `#define` it there, or do you prefer to place it into `src/Makefile`?

**Comment by capr** [comment]
OK I figured it out. the Makefile adds all `.c` files including dasm_x86.c where DASM_CHECKS is defined. You don't have to do anything. This _should work_ as is. Try to clone/make it all from scratch and see if you get the error again.

**Comment by hb9cwp** [comment]
@capr What do you mean by "clone/make it all from scratch" and "should work"? Did you change anything? Where? dasm_x86.c does not define DASM_CHECKS, at least not in the branch esp2.

**Comment by capr** [comment]
Oh, it doesn't? I see, yet another hack to satisfy the build system :) Fixed.

**Comment by capr** [comment]
I mean I fixed it in https://github.com/SnabbCo/snabbswitch/pull/709/commits

**Comment by hb9cwp** [comment]
Well, that's why I proposed to #define/#undef DASM_CHECKS in dasm_proto.h in https://github.com/hb9cwp/snabbswitch/commit/34af7c03c8ef16c5e5d66f05fa9785457c668691
Would it not be cleaner / more obvious to add -DDASM_CHECKS into the Makefile, and also fix the code path for the case when DASM_CHECKS is #undef'd, as proposed in the same PR?

**Comment by capr** [comment]
dasm_proto.h is from LuaJIT/LuaJIT which will never accept that :) The best way really is to add DASM_CHECKS to the makefile and leave the rest as it is in the upstream. As for fixing the case where DASM_CHECKS is not defined, I'd say there's nothing to fix because DASM_CHECKS should be defined (but if you insist, you can pcall the lookup in dasm.lua).

**Comment by hb9cwp** [comment]
Thanks, you are the maintainer with the commit bit for master. I only try to squash problems which prevent me from using lib.ipsec.esp, and to propose solutions :-)

**Pull request merged**
