### PR TITLE
Merge wingo-next to max-next

### PR DESCRIPTION
**Pull request by wingo**
I'm going to try to open merges on Monday.  Usually I would break out a separate PR for the merge, to allow `wingo-next` to move forward on its own without perturbing this review, but I'm going to be busy the next couple days and so this is easy enough.  Please take a look @eugeneia, and let me know if some other form for this is better for you.  FYI to @lukego about this workflow; suggestions welcome of course.

### CODE REVIEW

**Comment by eugeneia** [comment]
I am not sure PRs on my fork are a good idea, no CI here and generally doesn't add much value beyond there being a discussion functionality. I propose the following:

Let's do it as we did previously, open a PR on snabbco/snabbswitch “Merge wingo-next for 20XX.XX release” to signal that its ready for merge (please open this against master). This way Luke or I can merge it when the time comes. You only need to open one merge PR every moth because new commits will be appended to the PR. Also, I will personally not merge `wingo-next` more often that once a month, as that would just increase overhead.

I do the same for Luke to merge with `max-next` and it works well.

**Comment by lukego** [comment]
@eugeneia we should sync up on this. I feel like I would like to be pulling from `max-next` and `wingo-next` once or twice per week. That would get changes flowing through the system and landing on next in a reasonable timeframe. The main reason I see for batching changes together is as a throughput optimization i.e. in 1-2 pulls per week we could be moving tens/hundreds/thousands of individual changes as the network grows.

Could also send the PR to the `max-next` mirror on SnabbCo repo. That would be visible, have SnabbBot coverage, and automatically close the PR once it is merged onto the target (in normal Github fashion).

**Comment by wingo** [comment]
The reason I made the PR to this branch was so that all your work would have to be would be pressing the merge button.  If you prefer to get PRs somewhere else I can do that though :)

**Comment by eugeneia** [comment]
@wingo I would prefer a PR on snabbco/snabbswitch “Merge wingo-next for 20XX.XX release” targeting `master`.

**Pull request closed without merging**
